ignorePackages:
  # These packages are dev tools and we don't need their typings.
  - nodemon
  - prettier
  # Can't upgrade these libraries yet since they require ESM.
  - chalk
  - detect-indent
  - ora
